    # Development Profile (Optional)
spring:
  config:
    activate:
      on-profile: dev
  
jpa:
    show-sql: true
    properties:
      hibernate:
        "format_sql": true

logging:
  level:
    com.student.student: DEBUG
    org.hibernate.SQL: DEBUG